<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713174055 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create telematics_record table (typed AVL columns, jsonb extras, dedup + BRIN indexes)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE telematics_record (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recorded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, altitude_m INT DEFAULT NULL, speed_kmh SMALLINT DEFAULT NULL, ignition BOOLEAN DEFAULT NULL, movement BOOLEAN DEFAULT NULL, gsm_signal SMALLINT DEFAULT NULL, total_odometer_m BIGINT DEFAULT NULL, engine_total_fuel_used_ml BIGINT DEFAULT NULL, extra JSONB DEFAULT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_record_device_recorded_at ON telematics_record (device_id, recorded_at)');
        $this->addSql('CREATE INDEX idx_record_recorded_at_brin ON telematics_record USING brin (recorded_at)');
        $this->addSql('ALTER TABLE telematics_record ADD CONSTRAINT FK_B3855D2194A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE telematics_record DROP CONSTRAINT FK_B3855D2194A4C7D4');
        $this->addSql('DROP TABLE telematics_record');
    }
}
