<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713190756 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create plate tables: append-only observation log and 231/232 staging';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE device_partial_plate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, part1 VARCHAR(32) DEFAULT NULL, part1_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL, part2 VARCHAR(32) DEFAULT NULL, part2_at TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_partial_plate_device ON device_partial_plate (device_id)');
        $this->addSql('CREATE TABLE device_plate_observation (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plate VARCHAR(64) NOT NULL, observed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL, device_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_plate_observation_plate ON device_plate_observation (plate)');
        $this->addSql('CREATE INDEX idx_plate_observation_device_observed_at ON device_plate_observation (device_id, observed_at)');
        $this->addSql('ALTER TABLE device_partial_plate ADD CONSTRAINT FK_44CE683B94A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE device_plate_observation ADD CONSTRAINT FK_78F29B4F94A4C7D4 FOREIGN KEY (device_id) REFERENCES device (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE device_partial_plate DROP CONSTRAINT FK_44CE683B94A4C7D4');
        $this->addSql('ALTER TABLE device_plate_observation DROP CONSTRAINT FK_78F29B4F94A4C7D4');
        $this->addSql('DROP TABLE device_partial_plate');
        $this->addSql('DROP TABLE device_plate_observation');
    }
}
